@startuml Processo de Atividade
start

:Iniciar sistema operacional;

fork
    :carregar sistema operacional;
fork again
    :Verificação de atualizações de software;
fork again
    :Inicialização de serviços e redes;
end fork 

:Fim inicialização;

stop
@enduml